name: Deploy Astro to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v4
        with:
          path: ./radiant-resonance
          node-version: 18
      - uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: dist
